spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: 123456
    url: jdbc:mysql://10.5.155.2:3306/sell?characterEncoding=utf-8&useSSL=false
  jpa:
    show-sql: true
  jackson:
    # 全局设置返回结果为null时不显示
    default-property-inclusion: non_null
  redis:
    host: 10.5.155.2
    port: 6379

server:
  context-path: /sell

#logging:
#  pattern:
#    console: "%d - %msg%n"
##  path: /var/log/tomcat/
#  file: /var/log/tomcat/sell.log
#  level:
#    com.imooc.LoggerTest: debug

wechat:
  #公众平台AppId和AppSecret用来前端买家客户进入点餐系统时获取用户的openid，id用于确认用户信息、支付、推送模板消息
  mpAppId: wx6462c6ab925d6bb0
  mpAppSecret: 909e64b02e5d923515640535e96a6d45
  #开放平台AppId和AppSecret用来后台管理卖家用户登录管理系统时扫码登录，获取到的是另一个openid
  openAppId: wx6462c6ab925d6bb0
  openAppSecret: 909e64b02e5d923515640535e96a6d45
  #商家平台信息用于微信支付
  mchId: 1483469312
  mchKey: 06C56A89949D617xxxxxxxxxxx
  keyPath: /var/weixin_cert/h5.p12
  notifyUrl: http://sell.gabear.xyz:8080/sell/pay/notify
  templateId:
    orderStatus: e-Cqq67QxD6YNI41iRiqawEYdFavW_7pc7LyEMb-yeQ

projectUrl:
  wechatMpAuthorize: http://sell.gabear.xyz:8080
  wechatOpenAuthorize: http://sell.gabear.xyz:8080
  sell: http://sell.gabear.xyz:8080
